### PR TITLE
Bug fixes and new features

### PR DESCRIPTION
**Pull request by aribornstein**
Removed fixed aspect ratio in imgAreaSelect so that tagging is useful.
image

### CODE REVIEW

**Comment by nadavbar** [comment]
@amiturgman  can you please merge this and also grant Ari write access?

**Comment by amiturgman** [comment]
@nadavbar i don't have admin on this repo...
probably since the CatalystCode deletion disaster...

@stefangordon can you please grant admin permissions? This is my repo :)

**Comment by amiturgman** [comment]
@aribornstein @nadavbar  I added you to the repo

**Comment by aribornstein** [comment]
Hi @amiturgman I made the changes you requested and added resizing support please let me know if i can merge :)

**Comment by amiturgman** [comment]
@aribornstein did you test these changes in all major browsers? chrome, edge, firefox?
also- i'll be happy to see this in action before the merge...

**Comment by aribornstein** [comment]
@amiturgman Can you code review the new additions :) We can test in Firefox and Edge together

**Pull request merged**
